### ISSUE TITLE
【Android】-【6.8.8003】【视频裁剪页面显示异常】

### ISSUE THREAD

**Issue by Dandelion1230** [LiteAVSDK/UGSV_Android#2]
【当前现象】
Android端使用UGCSDK时，选择多个视频后，进行拼接，拼接失败，但是也进入到了视频裁剪页面。视频裁剪页面显示异常

【复现概率】
 偶现

【SDK名】
TXLiteAVSDK_UGC

【SDK版本】
LiteAVSDK_UGC_6.8.8003

【机型】
oppo r11

【复现途径】
1. 选择视频
2. 进入视频拼接界面
3. 进入视频裁剪页面（出现bug）

【Demo 复现途径】
不可复现 偶发

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等
![F281FB77-4AF9-4d3d-A4E9-1D74DA74EB54](https://user-images.githubusercontent.com/16744604/76076705-56ae6380-5fda-11ea-9436-a0a84e84045b.png)
![1024](https://user-images.githubusercontent.com/16744604/76076722-5d3cdb00-5fda-11ea-8f2a-db658c7b861f.png)

**Comment by yuejiaoli** [comment]
可以判断拼接出现错误后，提示，不跳转到裁剪界面
