### ISSUE TITLE
【Android】-【LiteAVSDK_UGC_7.1.8771】【短视频裁剪预览，31秒的视频，实际只播放了20秒就从头开始了（有的4 5 秒的视频，只播放了3 4 秒），有个视频必现，其他app可正常播放】

### ISSUE THREAD

**Issue by 1940913858** [LiteAVSDK/UGSV_Android#3]
【当前现象】
31秒的视频，实际只播放了20秒就从头开始了

【复现概率】
必现

【SDK名】
LiteAVSDK_UGC_7.1.8771

【SDK版本】
LiteAVSDK_UGC_7.1.8771

【机型】
所有机型

【复现途径】
1.直接打开裁剪界面，调整最大时长到60s ，然后播放该视频

【Demo 复现途径】

-
- 可复现

【相关附件】

> 请在附件中添加相关视频、日志，截图、操作视频等

**Comment by yuejiaoli** [comment]
请确认用其他播放器播放该视频是否20秒之后视频画面是否静止不动，如果20秒之后只播放声音，视频画面静止不动，说明后半截没有视频画面，所以只能播放到20秒

**Comment by whalehe** [comment]
您好，可以更新到最新版本7.4，如果还有问题，麻烦附上日志信息，或者截图。
