### ISSUE TITLE
【Android】-【Demo下载无法运行】

### ISSUE THREAD

**Issue by jerryswift** [LiteAVSDK/UGSV_Android#4]
1.使用最新版本demo；由于AS版本为3.6.2故升级了部分插件版本；
2.buildToolsVersion版本为28.0.3；com.android.tools.build:gradle版本为3.5.1；gradle版本为5.4.1-all；support库版本为28.0.0；
3.编译没有错误，运行提示
More than one file was found with OS independent path 'lib/arm64-v8a/librsjni.so'

**Comment by whalehe** [comment]
您好，可以更新到最新版本7.4，如果还有问题，麻烦附上日志信息，或者截图。
