### ISSUE TITLE
【Android/iOS】-【1.2.1234】【videoediter 播放视频回调报错】

### ISSUE THREAD

**Issue by i91h1r** [LiteAVSDK/UGSV_Android#5]
【当前现象】
线上报大量这个问题 

Attempt to invoke virtual method 'int com.tencent.liteav.videoediter.ffmpeg.jni.TXFFQuickJointerJNI.start()' on a null object reference
com.tencent.liteav.videoediter.ffmpeg.b$2.run(TXQuickJoiner.java:150)

【复现概率】
偶现 大概10 次会出现3次

【SDK名】
TXLiteAVSDK_Professional

【SDK版本】
7.2

【机型】
android 手机
【复现途径】

调用sdk 中播放视频videoediter 中回调出现

【Demo 复现途径】
可复现  / 不可复现
1. 点击 ...
2. 进入 ..
3. 等待 ...
4. 出现 Bug

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by i91h1r** [comment]
线上第一次出现问题时间是 4.4号 是不是7.0 版本出现得问题 ？

**Comment by whalehe** [comment]
您好，可以更新到最新版本7.4，如果还有问题，麻烦附上日志信息，或者截图。
