### ISSUE TITLE
【Android】-【LiteAVSDK_Professional_7.2.8927.aar】【从图库选择视频时进入裁剪点击下一步生成视频模糊】

### ISSUE THREAD

**Issue by z448401921** [LiteAVSDK/UGSV_Android#7]
【当前现象】
图库选择视频点击下一步进入编辑视频模糊

【复现概率】
必现 

【SDK名】
 TXLiteAVSDK_Professional
【SDK版本】
7.2.8927.

【机型】
华为p20

【复现途径】
1. 特效编辑-选择视频-视频裁剪-视频编辑
2. ProcessKit类下editer.processVideo();

【Demo 复现途径】
可复现  / 不可复现
1. 官方工具包
2. 短视频-特效编辑-选择视频-下一步

【相关附件】

**Comment by whalehe** [comment]
您好，可以更新下我们最新版本7.4，如果还有问题，烦请附上日志或者截图信息。
