### ISSUE TITLE
【Android】-【6.9】【根据时间获取缩略图】

### ISSUE THREAD

**Issue by inshyma** [LiteAVSDK/UGSV_Android#8]
【当前现象】
1. TXVideoEditer 类没有"txVideoEditer.getThumbnailList(list, 200, 200);"方法
2. "public void getThumbnail(List<Long> var1, int var2, int var3, boolean var4, TXVideoEditer.TXThumbnailListener var5) "  方法调用第三次就会失效 截取的图片不是指定时间的图片
【复现概率】
必现 

【SDK名】
TXLiteAVSDK_UGC / TXLiteAVSDK_Professional / TXLiteAVSDK_Enterprise

【SDK版本】
  6.9

【机型】
必现

【复现途径】
1. 调用 getThumbnail API

【Demo 复现途径】
  demo没有调用这个方法

【相关附件】
请在附件中添加相关视频、日志，截图、操作视频等

**Comment by whalehe** [comment]
您好，可以更新到最新版本7.4，如果还有问题，麻烦附上日志信息，或者截图。
